---
output:
  html_document: default
  pdf_document: default
---


```{r}
link="https://github.com/SamHenkels47/Project-1/raw/main/R%20sheet.xlsx"

library(rio)
mydata=import(link)
```

```{r}
mydata1=mydata[order(-mydata$SEMI_EXPORTS),]
```

```{r}
library(ggplot2)
base=ggplot(data=mydata1,aes(x=Country,y=SEMI_EXPORTS,fill=Country ))+scale_x_discrete(limits=mydata1$Country)
base1= base + theme_classic()



```

```{r}
plot1 = base1 + geom_bar(stat = 'identity') 
plot1
```
```{r}
titleText='Semiconductor Exports from Oregon in 2021'
sourceText='Source: US Census Bureau'

plot2 = plot1 + labs(title=titleText,
                     x ="Export Destination", 
                     y = "Exports in $ Billions",
                     caption = sourceText) 

plot2

```
```{r}
plot3 = plot2 + theme(plot.caption = element_text(hjust = 0), 
                      plot.title = element_text(hjust = 0.5))
plot3
```

```{r}
plot4 = plot3 +  geom_text(aes(label = SEMI_EXPORTS), nudge_y = .5)

plot4
```
```{r}
plot5 = plot4 + coord_flip()
plot5
```
```{r}
saveRDS(plot5,file = 'chart1.rds')
saveRDS(plot5,file='chart1.rds')

```
